-- ===========================================================================
--  0003 — demo accounts: intentionally a no-op
--
--  An earlier version of this migration INSERTed rows straight into auth.users.
--  That is not safe, and it broke a live project.
--
--  WHY IT BROKE
--    GoTrue scans several varchar columns on auth.users (confirmation_token,
--    recovery_token, email_change*, phone_change*, reauthentication_token) into
--    plain Go strings. Not all of those columns carry a database default, so an
--    INSERT that omits them leaves NULLs that GoTrue cannot read back. The whole
--    auth API then returns 500 — "Database error finding users" on listing,
--    "Database error querying schema" on sign-in — because those queries scan
--    across rows rather than just the affected ones. The damage is not even
--    self-repairing: the Admin API cannot delete such a row, because deleting it
--    reads it first.
--
--    The exception handler wrapped around the old block did not help. The INSERT
--    succeeded; the rows were only invalid to the layer above.
--
--  WHAT TO DO INSTEAD
--    Create users through the Auth Admin API, which populates every column the
--    way GoTrue expects and can confirm the address in the same call:
--
--      bun run scripts/create-demo-users.ts
--
--  Already ran the old version? scripts/repair-auth-users.sql heals it.
--
--  Kept as a no-op rather than deleted so the migration journal stays contiguous
--  for databases that already recorded 0003 as applied.
-- ===========================================================================

SELECT 'Demo accounts are created by scripts/create-demo-users.ts, not by a migration.' AS note;
